# Generated by Django 3.1.8 on 2021-04-06 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pid', models.CharField(max_length=256)),
                ('actual_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('slug', models.SlugField(max_length=264, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_items', to='home.category')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
