# Generated by Django 3.1.8 on 2021-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cat_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='cat_items',
            name='image',
            field=models.ImageField(upload_to='static/home/images'),
        ),
    ]
