# Generated by Django 3.1.8 on 2021-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='guest', max_length=256),
        ),
    ]
