# Generated by Django 3.1.8 on 2021-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210416_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=256)),
                ('prod_price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('cust_name', models.CharField(max_length=256)),
                ('cust_cell', models.CharField(max_length=256)),
                ('cust_whatsapp', models.CharField(max_length=256)),
                ('cust_aadr', models.CharField(max_length=1024)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default='Guest', max_length=256, null=True),
        ),
    ]
