# Generated by Django 3.1.8 on 2021-04-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210420_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorder',
            old_name='cust_aadr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='myorder',
            old_name='cust_cell',
            new_name='cell',
        ),
        migrations.RenameField(
            model_name='myorder',
            old_name='cust_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='myorder',
            old_name='cust_whatsapp',
            new_name='whatsapp',
        ),
    ]
