# Generated by Django 3.1.8 on 2021-04-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210420_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_items',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/home/images'),
        ),
        migrations.AddField(
            model_name='cat_items',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='static/home/images'),
        ),
    ]
